# Environment variables
# - HOST_NAME
# - USER_NAME
 
version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.1-browsers
    steps:
      - checkout
 
      - add_ssh_keys:
          fingerprints:
            - "ac:f8:02:1c:ce:ed:fb:94:5a:60:62:9d:ac:c3:7f:cf"
 
      - run:
          name: Start master deploy
          command: |
            ssh  -o StrictHostKeyChecking=no $USER_NAME@$HOST_NAME "cd /var/www/html/pws/2019; git pull origin master"
